name: Loki Alert Rules Validation

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - 'rules/prod/loki/*'

jobs:
  loki-alert-rules:
    name: Loki Alert Rules
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Download lokitool
      env:
        LOKITOOL_VERSION: 3.5.3
      run: |
        url="https://github.com/grafana/loki/releases/download/v$LOKITOOL_VERSION/lokitool-linux-amd64.zip"
        wget "$url" -O ./lokitool.zip
        unzip ./lokitool.zip -d lokitool

    - name: Check alert rules
      run: |
        ./lokitool/lokitool-linux-amd64 rules check --rule-dirs ./rules/prod/loki
